name: build-weather-ios
on:
  pull_request:
    branches:
      - "develop"
concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Tests & Generate code coverage
        env:
          GITHUB_API_TOKEN: ${{secrets.PERSONAL_API_TOKEN}}
        run: |
          bundle lock --add-platform x86_64-darwin-19
          bundle exec fastlane tests
